### PR TITLE
Upgrade repoter to 0.1.0 - a lot of changes & modes, with backward compatibility

### PR DESCRIPTION
**Pull request by marcinlesek**
Hello all!

Firstly, thanks @Shafied to create this reporter, well done! 🎉 A few days ago I had a need to create integration from my TestCafe with Slack and I started digging for ready to use libraries. This one was great, but it didn't have a lot of options to configure and wasn't maintained for about **2 years**. A moment into code and I decided to **boost a bit** capabilities that this reporter can do. Due to the fact, that a lot of people are using it, I created changes in a soft way, to allow **backward compatibility** and don't stop working in all projects after an upgrade.

The most crucial change is report messages styles (this one is from `summary` type, short & condensed):
slack-report-success
slack-report-failed

Here is a list of all the changes I made:
- Change report messages (add emojis, text formatters, new data to summary),
- Add logging levels (allow to change if we want a short report or get every test with error stack trace),
- Add quiet mode (disable logging to terminal information about sending messages to slack during execution),
- Little code refactor, move some code into separate modules,
- Remove old & deprecated dependencies,
- Create a separate config, which relays on the configuration in `.testcaferc.json`, after that on `.env` global variables and after that on default values,
- Update generated tests (from scaffolded template of TestCafe reporter),
- Update README about how it's looks like, installation, all configuration options & steps,
- Update `.travis.yml` to build the library,
- Refactor code consistency.

I'm open for feedback, hope this version will be more useful, in my case was priceless. In future, I want to create some more tests like only basics ones from TestCafe scaffold project and upgrade dependencies (like gulp to `4.0.0^` and TestCafe to `1.x.x^`).

Best,
Marcin

### CODE REVIEW

**Comment by njain2-rms** [comment]
I would love to have these features merged into the branch so that we can start using them

**Comment by marcinlesek** [comment]
Thanks @njain2-rms for your feedback. If you want to start using them straightforwardly, you could add it directly from my fork:
`yarn add marcinlesek/testcafe-reporter-slack`

If @Shafied approve this changes, then you can change it to default one.

Best,
Marcin

**Comment by Shafied** [comment]
Hey @marcinlesek. I wasnt really active on github the last period. Since the companies I've been working for where using Github. Nice that you are also created and fixed some stuff. I approved and merged it all

**Comment by marcinlesek** [comment]
Thanks @Shafied for approve and merge. Could you provide any contact to you, where we could be in touch in case of new PRs or changes? 😉

**Comment by Shafied** [comment]
If I'm not mistaken you should be a collaborator now. Or at least I invited you to be one. So you can do it yourself

**Comment by marcinlesek** [comment]
Got it, thanks @Shafied. 🎉

**Pull request merged**
